shutdown_costmaps: false

planner_frequency: 2.0
planner_patience: 3.0

controller_frequency: 10.0
controller_patience: 15.0

oscillation_timeout: 7.5
oscillation_distance: 0.2

conservative_reset_dist: 3.0

recovery_behavior_enabled: true
recovery_behaviors: [
    {
      name: conservative_reset,
      type: clear_costmap_recovery/ClearCostmapRecovery,
    },
    { name: rotate_recovery, type: rotate_recovery/RotateRecovery },
    { name: straf_recovery, type: straf_recovery/StrafRecovery },
    {
      name: aggressive_reset,
      type: clear_costmap_recovery/ClearCostmapRecovery,
    },
  ] #default

conservative_reset:
  reset_distance: 3.0

rotate_recovery:
  timeout: 5.0

straf_recovery:
  enabled: true
  frequency: 20.0
  go_to_goal_distance_threshold: 0.0
  maximum_translate_distance: 1.5
  minimum_translate_distance: 0.1
  increase_distance_threshold: 0.025
  straf_vel: 0.15
  timeout: 10.0
  obstacle_find_interval: 0.5
  xy_goal_tolerance: 0.1

aggressive_reset:
  reset_distance: 1.0
