local_costmap:
  plugins:
    - { name: static_map, type: "costmap_2d::StaticLayer" }
    - { name: keep_out_layer, type: "costmap_2d::KeepOutLayer" }
    - { name: obstacle_layer, type: "costmap_2d::ObstacleLayer" }
    - { name: inflation_layer, type: "costmap_2d::InflationLayer" }
