local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05

  obstacle_layer:
    observation_sources: scan
    scan:
      {
        topic: /rplidar/scan,
        sensor_frame: laser_link,
        observation_persistence: 0.0,
        expected_update_rate: 0.8,
        data_type: LaserScan,
        clearing: true,
        marking: true,
        max_obstacle_height: 2.0,
        min_obstacle_height: 0.0,
        obstacle_range: 2.5,
        raytrace_range: 5.0,
        inf_is_valid: false,
      }
  keep_out_layer:
    enabled: true
    fill_zones: true

  inflation_layer:
    enabled: true
    cost_scaling_factor: 10.0 # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius: 0.5 # max. distance from an obstacle at which costs are incurred for planning paths.

