local_costmap:
  global_frame: odom
  robot_base_frame: base_link

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: false
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05

  keep_out_layer:
    enabled: true
    fill_zones: true

  inflation_layer:
    enabled: true
    cost_scaling_factor: 5.0 # exponential rate at which the obstacle cost drops off (default: 10)
    inflation_radius: 0.35 # max. distance from an obstacle at which costs are incurred for planning paths.

