obstacle_range: 3.0
raytrace_range: 3.5

footprint: [[-0.14, -0.12], [-0.14, 0.12], [0.14, 0.12], [0.14, -0.12]]

inflation_radius: 3.0
cost_scaling_factor: 3.0

map_type: costmap
observation_sources: scan
scan:
  {
    sensor_frame: laser_link,
    data_type: LaserScan,
    topic: /rplidar/scan,
    marking: true,
    clearing: true,
  }
