footprint: [[-0.16, -0.12], [-0.16, 0.12], [0.16, 0.12], [0.16, -0.12]]

map_type: costmap
observation_sources: scan merged_rgbd_lidar_scan
scan:
  {
    sensor_frame: laser_link,
    data_type: LaserScan,
    topic: /rplidar/scan,
    marking: true,
    clearing: true,
  }
merged_rgbd_lidar_scan:
  {
    data_type: LaserScan,
    topic: /scan_multi,
    marking: true,
    clearing: true,
    inf_is_valid: true,
  }
